services:
  backend:
    image: ${DOCKERHUB_USERNAME}/backend:${IMAGE_TAG}
    container_name: app-dev-backend
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:${IMAGE_TAG}
    container_name: app-dev-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
