services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${IMAGE_TAG}
    container_name: app-prod-backend
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:${IMAGE_TAG}
    container_name: app-prod-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
