package com.ssafy.codefarm.hint.service;

import com.ssafy.codefarm.hint.dto.ai.AIHintRequest;
import com.ssafy.codefarm.hint.dto.ai.AIHintResponse;
import com.ssafy.codefarm.hint.entity.Hint;
import com.ssafy.codefarm.hint.entity.HintType;
import com.ssafy.codefarm.hint.repository.HintRepository;
import com.ssafy.codefarm.session.dto.redis.CodeSnapshotRedisDto;
import com.ssafy.codefarm.session.dto.redis.PreviousJudgementRedisDto;
import com.ssafy.codefarm.session.entity.Session;
import com.ssafy.codefarm.session.entity.SessionStatus;
import com.ssafy.codefarm.session.repository.SessionRepository;
import com.ssafy.codefarm.session.service.SessionCodeRedisService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class HintProcessingService {

    private final SessionRepository sessionRepository;
    private final SessionCodeRedisService sessionCodeRedisService;
    private final AIHintServerClient aiHintServerClient;
    private final HintRepository hintRepository;
    private final HintService hintService;

    @Transactional
    public boolean  process(Long sessionId) {

        log.debug("Starting auto hint processing. sessionId={}", sessionId);

        Session session = sessionRepository.findById(sessionId).orElse(null);

        if (session == null) {
            log.warn("Session not found during auto hint processing. sessionId={}", sessionId);
            return false;
        }
        if (session.getStatus() != SessionStatus.ACTIVE) {
            log.info("Session is not active. Stopping scheduler. sessionId={}, status={}", sessionId, session.getStatus());
            return false;
        }

        // 24시간 초과 체크
        if (Duration.between(session.getStartedAt(), LocalDateTime.now()).toHours() >= 24) {
            log.info("Session expired (24h). Closing session. sessionId={}", sessionId);
            session.close();
            sessionCodeRedisService.delete(sessionId);
            hintService.clearSession(sessionId);
            return false;
        }

        List<CodeSnapshotRedisDto> history = sessionCodeRedisService.getSnapshots(sessionId);
        List<PreviousJudgementRedisDto> previous = sessionCodeRedisService.getPreviousJudgements(sessionId);

        List<CodeSnapshotRedisDto> filtered = filterRecentHistory(history);

        AIHintRequest request = AIHintRequest.of(
                session,
                session.getUser(),
                session.getProblem(),
                null,
                filtered,
                previous
        );

        log.debug("Requesting AI hint. sessionId={}, historySize={}", sessionId, filtered.size());
        AIHintResponse response = aiHintServerClient.request(sessionId, request);
        if (response == null) {
            log.warn("Received null response from AI hint server. sessionId={}", sessionId);
            return true;
        }

        String hintContent = response.hint();
        AIHintResponse.CurrentJudgement cj = response.current_judgement();

        sessionCodeRedisService.appendJudgement(
                sessionId,
                PreviousJudgementRedisDto.builder()
                        .analysis(cj.analysis())
                        .mistakeType(cj.mistake_type())
                        .judgedAt(LocalDateTime.now())
                        .hint(hintContent)
                        .build()
        );

        if (hintContent == null || hintContent.isBlank()) {
            log.debug("No hint generated by AI. sessionId={}", sessionId);
            return true;
        }

        log.info("AI hint generated. sessionId={}, content_length={}", sessionId, hintContent.length());

        Hint hint = Hint.builder()
                .session(session)
                .hintType(HintType.AUTO)
                .content(hintContent)
                .build();

        hintRepository.save(hint);

        hintService.sendAutoHint(
                sessionId,
                Map.of(
                        "hintId", hint.getId(),
                        "hintType", hint.getHintType(),
                        "content", hint.getContent(),
                        "isViewed", hint.getIsViewed(),
                        "createdAt", hint.getCreatedAt()
                )
        );

        return true;
    }

    private List<CodeSnapshotRedisDto> filterRecentHistory(List<CodeSnapshotRedisDto> history) {

        if (history == null || history.isEmpty()) {
            return List.of();
        }

        LocalDateTime threshold = LocalDateTime.now().minusMinutes(5);

        List<CodeSnapshotRedisDto> filtered =
                history.stream()
                        .filter(h -> h.getSavedAt().isAfter(threshold))
                        .toList();

        if (filtered.isEmpty()) {
            return List.of(history.get(history.size() - 1));
        }

        return filtered;
    }
}
