services:
  api:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: api-dev
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    build:
      context: ../../infra/nginx
      dockerfile: Dockerfile
    container_name: web-dev
    ports:
      - "80:80"
    restart: unless-stopped

  postgres:
    container_name: postgres-dev
    restart: unless-stopped

  redis:
    container_name: redis-dev
    restart: unless-stopped
