services:
  api:
    container_name: api-prod
    restart: always

  web:
    container_name: web-prod
    ports:
      - "80:80"
    restart: always

  postgres:
    container_name: postgres-prod
    restart: always

  redis:
    container_name: redis-prod
    restart: always
